global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'information-broker-metrics'
    static_configs:
      - targets: ['rss-monitor:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s
    params:
      format: ['prometheus']

  - job_name: 'information-broker-health'
    static_configs:
      - targets: ['rss-monitor:8080']
    metrics_path: '/health'
    scrape_interval: 15s
    scrape_timeout: 5s
    metric_relabel_configs:
      - source_labels: [__name__]
        regex: 'up|probe_.*'
        action: keep